---
api:
  protocol: "HTTPS"
  port: 443
  host: "${spring.profiles}.itservices.hawaiianairlines.com"
---
spring:
  profiles: "dev"
api:
  url:
    process.pss.passengers.host: "${api.host}/proc-pss-passengers"
    process.pss.flights.host: "${api.host}/proc-pss-flights"
---
spring:
  profiles: "test"
api:
  url:
    process.pss.passengers.host: "${api.host}/proc-pss-passengers"
    process.pss.flights.host: "${api.host}/proc-pss-flights"
---
spring:
  profiles: "prod"
api:
  url:
    process.pss.passengers.host: "${api.host}/proc-pss-passengers"
    process.pss.flights.host: "${api.host}/proc-pss-flights"
