---
api:
  protocol: "HTTPS"
  port: 443
  host: "${spring.profiles}.itservices.hawaiianairlines.com"
  connection.idle.timeout: 30000
  response.timeout: 30000
---
spring:
  profiles: "dev"
json:
  logger:
    mq:
      clientAppId: "dbd44f20990842f08aef6940c6cd2e26"
      clientSecret: "SOME_ENCRYPED_VALUE"
---
spring:
  profiles: "test"
json:
  logger:
    mq:
      clientAppId: "dbd44f20990842f08aef6940c6cd2e26"
      clientSecret: "SOME_ENCRYPED_VALUE"
---
spring:
  profiles: "prod"
json:
  logger:
    mq:
      clientAppId: "dbd44f20990842f08aef6940c6cd2e26"
      clientSecret: "SOME_ENCRYPED_VALUE"
