spring:
  profiles: dev
api:
  url: 
    base: https://dev.itservices.hawaiianairlines.com
    process.pss.passengers.host: ${api.url.base}/proc-pss-passengers
    process.pss.flights.host: ${api.url.base}/proc-pss-flights
---
spring:
  profiles: test
nginx:
  server:
    name: test.example.com
