api:
  url:
    protocol: HTTPS
    port: 443
    base: ${spring.profiles}.itservices.hawaiianairlines.com
spring:
  profiles: dev
api:
  url:
    process.pss.passengers.host: ${api.url.base}/proc-pss-passengers
    process.pss.flights.host: ${api.url.base}/proc-pss-flights
spring:
  profiles: test
nginx:
  server:
    name: test.example.com
