api:
  protocol: HTTPS
  port: 443
  base: ${spring.profiles}.itservices.hawaiianairlines.com
---
spring:
  profiles: dev
api:
  url:
    process.pss.passengers.host: ${api.base}/proc-pss-passengers
    process.pss.flights.host: ${api.base}/proc-pss-flights
---
spring:
  profiles: test
nginx:
  server:
    name: test.example.com
