---
api:
  protocol: "HTTPS"
  port: 443
  host: "${spring.profiles}.itservices.hawaiianairlines.com"
---
spring:
  profiles: "dev"
api:
  url:
    ha.sys.ods.logs.base: "/ha-sys-ods-logs/api"
    ha.sys.ods.flights.datastore.base: "/ha-sys-ods-flights-datastore/api"
    ha.sys.ods.flights.ssim.btc.inb.dev.base: "/ha-sys-ods-flights-ssim-btc-inb-dev/api"
    process.carts.api.base: "/process-carts-api/api"
    sys.sabre.passengers.api.dev.base: "/sys-sabre-passengers-api-dev/api"
    sys.keymanager.api.dev.base: "/sys-keymanager-api-dev/api"
    ha.net.tools.dev.base: "/ha-net-tools-dev/api"
    sys.sabre.common.api.dev.base: "/sys-sabre-common-api-dev/api"
    ha.sys.ods.logs.api.impl.int.base: "/ha-sys-ods-logs-api-impl-int/api"
    proc.design.center.pub.status.base: "/proc-design-center-pub-status/api"
    experience.web.base: "/experience-web/api"
    process.payments.api.dev.base: "/process-payments-api-dev/api"
    process.auth.base: "/process-auth/api"
    proc.pss.catalogs.api.dev.base: "/proc-pss-catalogs-api-dev/api"
    ha.sys.ods.flights.ssim.btc.inb.int.base: "/ha-sys-ods-flights-ssim-btc-inb-int/api"
    ha.sys.ods.flights.datastore.api.impl.int.base: "/ha-sys-ods-flights-datastore-api-impl-int/api"
    system.sabre.flights.api.andres.base: "/system-sabre-flights-api-andres/api"
    experience.web.api.dev.base: "/experience-web-api-dev/api"
    timothy.sys.sabre.flights.api.dev.base: "/timothy-sys-sabre-flights-api-dev/api"
    ha.sys.ods.flights.actual.oub.dev.base: "/ha-sys-ods-flights-actual-oub-dev/api"
    proc.pss.trips.api.dev.base: "/proc-pss-trips-api-dev/api"
    ha.sys.ods.reference.datastore.api.dev.base: "/ha-sys-ods-reference-datastore-api-dev/api"
    experience.mobile.dlb.base: "/experience-mobile-dlb/api"
    proc.pss.flights.base: "/proc-pss-flights/api"
    proc.flights.base: "/proc-flights/api"
    ha.sys.ods.flights.actual.oub.int.base: "/ha-sys-ods-flights-actual-oub-int/api"
    proc.trips.api.dev.base: "/proc-trips-api-dev/api"
    process.catalogs.base: "/process-catalogs/api"
    experience.mobile.base: "/experience-mobile/api"
    ha.proc.ods.flights.base: "/ha-proc-ods-flights/api"
    ha.sys.ods.flights.actual.inb.int.base: "/ha-sys-ods-flights-actual-inb-int/api"
    ha.sys.vacationpackage.api.base: "/ha-sys-vacationpackage-api/api"
    api.manager.exp.base: "/api-manager-exp/api"
    exp.mobile.api.mock.base: "/exp-mobile-api-mock/api"
    proc.pss.passengers.api.dev.base: "/proc-pss-passengers-api-dev/api"
    process.users.api.dev.base: "/process-users-api-dev/api"
    sys.sabre.flights.api.dev.base: "/sys-sabre-flights-api-dev/api"
    system.customer.ods.api.dev.base: "/system-customer-ods-api-dev/api"
    system.hawaiianmiles.users.api.dev.base: "/system-hawaiianmiles-users-api-dev/api"
    wmqsample.base: "/wmqsample/api"
    process.auth.api.dev.base: "/process-auth-api-dev/api"
    ha.sys.ods.flights.actual.inb.dev.base: "/ha-sys-ods-flights-actual-inb-dev/api"
    ha.exp.vacationpackage.api.base: "/ha-exp-vacationpackage-api/api"
    sys.atpco.api.dev.base: "/sys-atpco-api-dev/api"
    ha.process.vacationpackage.api.base: "/ha-process-vacationpackage-api/api"
    ha.sys.ods.flights.conntest.lab.base: "/ha-sys-ods-flights-conntest-lab/api"
    ztst.ods.mongo.date.lab.base: "/ztst-ods-mongo-date-lab/api"
    system.barcode.generator.dev.base: "/system-barcode-generator-dev/api"
    system.encryption.api.base: "/system-encryption-api/api"
    sys.sabre.trips.api.dev.base: "/sys-sabre-trips-api-dev/api"
    system.rules.api.dev.base: "/system-rules-api-dev/api"
    exchange.exp.base: "/exchange-exp/api"
    system.oauth2.auth.api.dev.base: "/system-oauth2-auth-api-dev/api"
---
spring:
  profiles: "test"
api:
  url:
    process.users.api.test.base: "/process-users-api-test/api"
    system.oauth2.auth.api.test.base: "/system-oauth2-auth-api-test/api"
    system.hawaiianmiles.users.api.test.base: "/system-hawaiianmiles-users-api-test/api"
    proc.design.center.pub.status.api.impl.tst.base: "/proc-design-center-pub-status-api-impl-tst/api"
    process.auth.api.impl.test.base: "/process-auth-api-impl-test/api"
    ha.sys.ods.flights.datastore.api.test.base: "/ha-sys-ods-flights-datastore-api-test/api"
    ha.sys.ods.flights.ssim.inb.test.base: "/ha-sys-ods-flights-ssim-inb-test/api"
    ha.sys.ods.logs.api.impl.test.base: "/ha-sys-ods-logs-api-impl-test/api"
    exp.mobile.api.mock.test.base: "/exp-mobile-api-mock-test/api"
    test.spec.bamboo.api.impl.test.base: "/test-spec-bamboo-api-impl-test/api"
    api.template.api.impl.test.base: "/api-template-api-impl-test/api"
    proc.flights.api.test.base: "/proc-flights-api-test/api"
    sys.sabre.passengers.api.test.base: "/sys-sabre-passengers-api-test/api"
    proc.pss.passengers.api.test.base: "/proc-pss-passengers-api-test/api"
    ha.net.tools.test.base: "/ha-net-tools-test/api"
    sys.sabre.trips.api.test.base: "/sys-sabre-trips-api-test/api"
    sys.sabre.common.api.test.base: "/sys-sabre-common-api-test/api"
    proc.pss.flights.api.test.base: "/proc-pss-flights-api-test/api"
    sys.sabre.flights.api.test.base: "/sys-sabre-flights-api-test/api"
    process.auth.api.test.base: "/process-auth-api-test/api"
---
spring:
  profiles: "prod"
api:
  url:
    test.spec.bamboo.api.impl.base: "/test-spec-bamboo-api-impl/api"
